### ISSUE TITLE
ユーザー名まわり

### ISSUE THREAD

**Issue by hyakkun** [trtd56/Bounen#1]
* 万が一名前が重複すると1つのデータを上書きしあってしまう
* うっかり名前に`/`などの文字を使うとデータ構造が壊れる
    * 参考 : [この辺](https://firebase.google.com/docs/database/web/structure-data?hl=ja#how_data_is_structured_its_a_json_tree)

対処の方向性案（どっちも実装の目処は立ってます）

* 名前のバリデーションだけつけておいて重複しないようにするのは運用でがんばる
    * [このあたり](https://kuroeveryday.blogspot.com/2017/10/vuejs-form-validation-with-input-element.html)を参考に
    * 運用でどう頑張るか、という話はある
* 最初に[`push()`](https://firebase.google.com/docs/reference/js/firebase.database.Reference?hl=ja#push)を使って一意キーを作っておく
    * この場合`params`に`username`とキーの両方が必要になる（うまくやれば後者だけでもいける？）
    * また、結果の画面に同じ名前が複数出ても結局どれが誰だってなるので、別途対策が必要
        * キーを持ったまま結果表示に遷移するパスを作るとか？

**Comment by trtd56** [comment]
重複に関しては、参加者で苗字が被っている人が1人しかいないから「基本苗字で」ってルールにすれば行けるんじゃないかなと思ってる
`/`は問題だから、修正しないと・・・
